### ISSUE TITLE
Delete unnecessary image directory

### ISSUE THREAD

**Issue by yuuki1224** [yamadasmith/playorder#2]
https://github.com/yamadasmith/playorder/tree/master/img/shop/images

これいらないっすね、pushする前に余分なものないか気をつけてください

**Comment by yuuki1224** [comment]
@yamadasmith これもっすね、終わったIssuesは、closeしてください

**Comment by yamadasmith** [comment]
了解です,,
なぜか、HTMLがぜんぜん使えなくなりました。死にそうですわ

**Comment by yuuki1224** [comment]
ちょっと意味がわからないっすね. plz explain @yamadasmith
